#!/usr/bin/env python3
"""
audit_digest.py — weekly editorial audit digest (human safety net).

Read-only over content/manifests/. Collects guides published in the last N days,
summarises the FLAG-tier (review) and any BLOCK-tier claims the gate detected,
and delivers a skimmable digest:
  - emails it via Resend if RESEND_API_KEY + a recipient are configured, AND
  - always writes it to $GITHUB_STEP_SUMMARY (so the Action run shows it) + stdout.

Nothing here blocks publishing — it is purely a review aid. Stdlib only.

    python3 scripts/audit_digest.py                 # last 7 days, print + email if configured
    python3 scripts/audit_digest.py --days 14 --no-email
"""
import argparse
import datetime
import json
import os
import sys
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FROM_ADDRESS = "Beat the Scam Audit <alerts@updates.beatthescam.com>"


def recipient() -> str:
    if os.getenv("DIGEST_TO"):
        return os.getenv("DIGEST_TO").strip()
    try:
        site = json.loads((ROOT / "content" / "site.json").read_text(encoding="utf-8"))
        return site.get("contact_email") or site.get("privacy_email") or ""
    except Exception:
        return ""


def load_recent(mdir: Path, days: int):
    cutoff = datetime.date.today() - datetime.timedelta(days=days)
    out = []
    for f in sorted(mdir.glob("*.json")):
        try:
            m = json.loads(f.read_text(encoding="utf-8"))
            pub = datetime.date.fromisoformat(str(m.get("date")))
        except Exception:
            continue
        if pub >= cutoff:
            out.append(m)
    return out


def build_digest(manifests, days: int):
    blocks, flags = [], []
    for m in manifests:
        for c in m.get("claims", []):
            row = (m.get("slug"), c.get("type"), c.get("text"))
            (blocks if c.get("severity") == "block" else flags).append(row)

    lines = [f"# Beat the Scam — weekly editorial audit ({len(manifests)} guides, last {days} days)", ""]
    if blocks:
        lines.append(f"## ⚠️ {len(blocks)} BLOCK-tier claim(s) in LIVE guides — should not happen, fix now")
        for slug, t, text in blocks:
            lines.append(f"- **[{t}]** `{slug}`: {text}")
        lines.append("")
    if flags:
        lines.append(f"## {len(flags)} claim(s) to verify")
        for slug, t, text in flags:
            lines.append(f"- **[{t}]** `{slug}`: {text}")
    else:
        lines.append("No high-stakes claims to review in this window. ✅")
    lines += ["", "_How to act: confirm each against the official source. For a good "
              "reporting email/number, add it to `content/sources.json`; for a wrong "
              "claim, fix the guide. Generated by scripts/audit_digest.py._"]
    return "\n".join(lines), len(blocks), len(flags)


def send_email(md: str):
    api_key = os.getenv("RESEND_API_KEY")
    to = recipient()
    if not api_key or not to:
        print(f"  (email skipped — RESEND_API_KEY set: {bool(api_key)}, recipient: {to or 'none'})")
        return False
    html = "<pre style=\"font:14px/1.5 -apple-system,Segoe UI,Roboto,sans-serif;white-space:pre-wrap\">" \
           + md.replace("&", "&amp;").replace("<", "&lt;") + "</pre>"
    body = json.dumps({
        "from": FROM_ADDRESS, "to": [to],
        "subject": "Beat the Scam — weekly editorial audit",
        "html": html, "text": md,
    }).encode("utf-8")
    req = urllib.request.Request("https://api.resend.com/emails", data=body, method="POST",
                                 headers={"Content-Type": "application/json",
                                          "Authorization": f"Bearer {api_key}",
                                          # urllib's default "Python-urllib/x.y" User-Agent gets
                                          # fingerprinted and blocked by Cloudflare (error 1010) in
                                          # front of api.resend.com — found 2026-08-27 on the first
                                          # live send. The other scripts here that call external
                                          # APIs (submit_indexnow.py, newsjacking_scan.py) already
                                          # set a real one for the same reason.
                                          "User-Agent": "BeatTheScam-AuditDigest/1.0"})
    try:
        with urllib.request.urlopen(req, timeout=20) as r:
            print(f"  digest emailed to {to} (HTTP {r.status})")
            return True
    except urllib.error.HTTPError as e:
        # Resend's response body names the actual cause (invalid key, a
        # sending-scope-restricted key, an unverified domain, …) — the bare
        # "HTTP Error 403: Forbidden" str(e) gives none of that (found
        # 2026-08-27: first live send attempt after RESEND_API_KEY was added
        # to GitHub Actions secrets failed 403 with no way to diagnose why).
        detail = e.read().decode("utf-8", "replace")[:500]
        print(f"  [warn] digest email failed: HTTP {e.code} {e.reason} — {detail}")
        return False
    except Exception as e:
        print(f"  [warn] digest email failed: {e}")
        return False


def main() -> int:
    ap = argparse.ArgumentParser(description="Weekly editorial audit digest")
    ap.add_argument("--days", type=int, default=7)
    ap.add_argument("--manifests", default=str(ROOT / "content" / "manifests"))
    ap.add_argument("--no-email", action="store_true")
    args = ap.parse_args()

    mdir = Path(args.manifests)
    if not mdir.exists():
        print("No manifests directory — nothing to audit.")
        return 0

    manifests = load_recent(mdir, args.days)
    md, n_block, n_flag = build_digest(manifests, args.days)
    print(md)

    summary = os.getenv("GITHUB_STEP_SUMMARY")
    if summary:
        try:
            with open(summary, "a", encoding="utf-8") as f:
                f.write(md + "\n")
        except Exception as e:
            print(f"  [warn] step summary write failed: {e}")

    if not args.no_email:
        send_email(md)

    print(f"\nSummary: {len(manifests)} guides in window | {n_block} block, {n_flag} flag.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
